// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4wGdhC6A5I68iEc-AxKzAnp-krfZQwSA',
    appId: '1:176373272495:web:e2fc537e14ca72e8bfa95a',
    messagingSenderId: '176373272495',
    projectId: 'test-app-b387d',
    authDomain: 'test-app-b387d.firebaseapp.com',
    storageBucket: 'test-app-b387d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZLPGMBuGKQpb7v3q_VTR0xUCjph9cljY',
    appId: '1:176373272495:android:fc2db783d224b1b0bfa95a',
    messagingSenderId: '176373272495',
    projectId: 'test-app-b387d',
    storageBucket: 'test-app-b387d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzk1Xe-c7-GKMWPIneIJLdXgiUBTgqdJI',
    appId: '1:176373272495:ios:e3882817779164b3bfa95a',
    messagingSenderId: '176373272495',
    projectId: 'test-app-b387d',
    storageBucket: 'test-app-b387d.firebasestorage.app',
    iosBundleId: 'com.example.maxpense',
  );
}
